"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[directory]
style = 'bold blue'

[git_branch]
style = 'bold yellow'

[git_commit]
style = 'bold green'

[git_state]
style = 'bold red'

[git_status]
style = 'bold purple'

[php]
style = 'bold purple'
